src/main/java/by/epam/terehovich/internetprovider/entity/Cabinet.java
package by.epam.terehovich.internetprovider.entity;

import by.epam.terehovich.internetprovider.dao.TariffDAO;
import by.epam.terehovich.internetprovider.exception.DAOexception;
import org.apache.log4j.Logger;

import java.util.GregorianCalendar;

/**
 * Created by Artyom on 13.08.2015.
 */
public class Cabinet extends Entity {
    private static final Logger LOGGER = Logger.getLogger(Cabinet.class);
    private int idTariff;
    private GregorianCalendar connectDate;
    private int money;
    private int status;

    public Cabinet(int id) {
        super(id);
    }

    public Cabinet(int id, int idTariff, GregorianCalendar connectDate, int money, int status){
        super(id);
        this.idTariff = idTariff;
        this.connectDate = connectDate;
        this.money = money;
        this.status = status;
    }

    public int getIdTariff() {
        return idTariff;
    }

    public void setIdTariff(int idTariff) {
        this.idTariff = idTariff;
    }

    public GregorianCalendar getConnectDate() {
        return connectDate;
    }

    public void setConnectDate(GregorianCalendar connectDate) {
        this.connectDate = connectDate;
    }

    public int getMoney() {
        return money;
    }

    public void setMoney(int money) {
        this.money = money;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }
    public String getTariffName(){
        TariffPlan tariffPlan = null;
        TariffDAO tariffDAO = new TariffDAO();
        try {
            tariffPlan =  tariffDAO.findById(idTariff);
        } catch (DAOexception daOexception) {
            LOGGER.error(daOexception);
        }
        return tariffPlan.getName();
    }
    public String getDateToString(){
        return connectDate.get(GregorianCalendar.DAY_OF_MONTH) + "." +
                (connectDate.get(GregorianCalendar.MONTH)+1) + "." +
                connectDate.get(GregorianCalendar.YEAR);
    }
}

src/main/webapp/jsp/admin-cabinet.jsp
<%--
  Created by IntelliJ IDEA.
  User: Artyom
  Date: 10.08.2015
  Time: 15:58
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@taglib uri="customtags" prefix="ctd" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<fmt:setLocale value="${sessionScope.lang}"/>
<fmt:setBundle basename="localization"/>
<html>
<head>
    <title><fmt:message key="page.admin-cabinet.title"/></title>
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/modal.css" type="text/css">
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/style/style.css" type="text/css">
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/tabs/tabs.css" type="text/css">
</head>
<body>
<c:import url="${pageContext.request.contextPath}/jsp/patterns/header.jsp"/>
<div class="tabs">
    <input id="tab1" type="radio" name="tabs" checked>
    <label for="tab1" title="Вкладка 1"><fmt:message key="page.cabinet.personal-info"/> </label>

    <input id="tab2" type="radio" name="tabs">
    <label for="tab2" title="Вкладка 2"><fmt:message key="page.admin-cabinet.users"/> </label>

    <input id="tab3" type="radio" name="tabs">
    <label for="tab3" title="Вкладка 3"><fmt:message key="page.admin-cabinet.apps"/> </label>

    <input id="tab4" type="radio" name="tabs">
    <label for="tab4" title="Вкладка 4"><fmt:message key="page.admin-cabinet.tariff.tariffs"/> </label>


    <section id="content1">
        <p>
        <table>
            <tr>
                <td>
                    <fmt:message key="page.cabinet.firstname"/>
                </td>
                <td>
                    ${sessionScope.account.firstname}
                </td>
            </tr>
            <tr>
                <td>
                    <fmt:message key="page.cabinet.lastname"/>
                </td>
                <td>
                    ${sessionScope.account.lastname}
                </td>
            </tr>
            <tr>
                <td>
                    <fmt:message key="page.cabinet.secondname"/>
                </td>
                <td>
                    ${sessionScope.account.secondname}
                </td>
            </tr>

        </table>
        <a href="#changepassword" class="openModal"><fmt:message key="page.cabinet.change-pass"/> </a>
        <aside id="changepassword" class="modal">
            <div>
                <form action="${pageContext.request.contextPath}/control" method="post" name="change-password"
                      class="form-registration">
                    <input name="command" type="hidden" value="changepass">
                    <table>
                        <tr>
                            <td><fmt:message key="page.cabinet.oldpass"/></td>
                            <td><input type="password" name="oldpass" size="15" maxlength="15"></td>
                        </tr>
                        <tr>
                            <td><fmt:message key="page.cabinet.newpass"/></td>
                            <td><input type="password" name="newpass" size="15" maxlength="15"></td>
                        </tr>
                        <tr>
                            <td><fmt:message key="page.cabinet.newpass2"/></td>
                            <td><input type="password" name="newpass2" size="15" maxlength="15"></td>
                        </tr>
                        <tr>
                            <td colspan="2"><input type="submit" name="submit"
                                                   value="<fmt:message key="button.edit"/> "></td>
                        </tr>
                    </table>
                </form>
                <a href="#close" title="Закрыть">Закрыть</a>
            </div>
        </aside>
        ${result}
        </p>
    </section>
    <section id="content2">
        <p>
        <table border="1">
            <tr>
                <td>ID</td>
                <td><fmt:message key="page.registration.login"/></td>
                <td><fmt:message key="page.admin-cabinet.full-name"/></td>
                <td><fmt:message key="page.admin-cabinet.role"/></td>
                <td><fmt:message key="page.cabinet.city"/></td>
            </tr>
            <ctd:user-table/>
        </table>
        </p>
    </section>
    <section id="content3">
        <p>
            TODO:applications
        </p>
    </section>
    <section id="content4">
        <p>
            ${status}
        <table>
            <tr>
                <td><fmt:message key="page.admin-cabinet.tariff.tariff-name"/> </td>
                <td><fmt:message key="page.admin-cabinet.tariff.speed"/> </td>
                <td><fmt:message key="page.admin-cabinet.tariff.Traffic"/> </td>
                <td><fmt:message key="page.admin-cabinet.tariff.licence-fee"/> </td>
            </tr>

            <jsp:useBean id="allTariffs" class="by.epam.terehovich.internetprovider.dao.TariffDAO" scope="page"/>
            <c:forEach items="${allTariffs.findAll()}" var="tariff">
                <tr>
                    <td>${tariff.name}</td>
                    <td>${tariff.speed}</td>
                    <td>${tariff.traffic}</td>
                    <td>${tariff.licenseFee}</td>
                </tr>
            </c:forEach>
        </table>
        <a href="#addtarif" class="openModal"><fmt:message key="button.create"/> </a>
        <aside id="addtarif" class="modal">
            <div>
                <form action="${pageContext.request.contextPath}/control" method="post" name="addtariff"
                      class="form-registration">
                    <input name="command" type="hidden" value="addtariff">
                    <table>
                        <tr>
                            <td><fmt:message key="page.admin-cabinet.tariff.tariff-name"/></td>
                            <td><input type="text" name="tariff-name" size="15" maxlength="15"></td>
                        </tr>
                        <tr>
                            <td><fmt:message key="page.admin-cabinet.tariff.licence-fee"/></td>
                            <td><input type="text" name="license-fee" size="15" maxlength="15"></td>
                        </tr>
                        <tr>
                            <td><fmt:message key="page.admin-cabinet.tariff.speed"/></td>
                            <td><input type="text" name="speed" size="15" maxlength="15"></td>
                        </tr>
                        <tr>
                            <td><fmt:message key="page.admin-cabinet.tariff.Traffic"/></td>
                            <td><input type="text" name="traffic" size="15" maxlength="15"></td>
                        </tr>
                        <tr>
                            <td colspan="2"><input type="submit" name="submit"
                                                   value="<fmt:message key="button.create"/> "></td>
                        </tr>
                    </table>
                </form>
                <a href="#close" title="Закрыть">Закрыть</a>
            </div>
        </aside>
        </p>
    </section>
</div>

</body>
</html>

src/main/webapp/jsp/cabinet.jsp
<%@ page import="by.epam.terehovich.internetprovider.resource.MessageManager" %>
<%--
  Created by IntelliJ IDEA.
  User: aterehovich
  Date: 22.7.15
  Time: 8.51
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<fmt:setLocale value="${sessionScope.lang}"/>
<fmt:setBundle basename="localization"/>
<html>
<head>
    <title><fmt:message key="page.cabinet.title"/> </title>
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/modal.css" type="text/css">
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/style/style.css" type="text/css">
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/tabs/tabs.css" type="text/css">
</head>
<c:import url="${pageContext.request.contextPath}/jsp/patterns/header.jsp"/>
<body>
<div class="tabs">
  <input id="tab1" type="radio" name="tabs" checked>
  <label for="tab1" title="Tab1"><fmt:message key="page.cabinet.personal-info"/> </label>

  <input id="tab2" type="radio" name="tabs">
  <label for="tab2" title="Tab2"><fmt:message key="page.cabinet.account-info"/> </label>

  <input id="tab3" type="radio" name="tabs">
  <label for="tab3" title="Tab3"><fmt:message key="page.cabinet.operations"/> </label>

  <section id="content1">
    <table>
      <tr>
        <td>
          <fmt:message key="page.cabinet.firstname"/>
        </td>
        <td>
          ${sessionScope.account.firstname}
        </td>
      </tr>
      <tr>
        <td>
          <fmt:message key="page.cabinet.lastname"/>
        </td>
        <td>
          ${sessionScope.account.lastname}
        </td>
      </tr>
      <tr>
        <td>
          <fmt:message key="page.cabinet.city"/>
        </td>
        <td>
          ${sessionScope.account.city}
        </td>
      </tr>
      <tr>
        <td>
          <fmt:message key="page.cabinet.address"/>
        </td>
        <td>
          ${sessionScope.account.address}
        </td>
      </tr>

    </table>
    <a href="#changepassword" class="openModal"><fmt:message key="page.cabinet.change-pass"/> </a>
    <aside id="changepassword" class="modal">
      <div>
        <form action="${pageContext.request.contextPath}/control" method="post" name="change-password" class="form-registration">
          <input name="command" type="hidden" value="changepass">
          <table>
            <tr>
              <td><fmt:message key="page.cabinet.oldpass"/> </td>
              <td><input type="password" name="oldpass" size="15" maxlength="15"> </td>
            </tr>
            <tr>
              <td><fmt:message key="page.cabinet.newpass"/> </td>
              <td><input type="password" name="newpass" size="15" maxlength="15"></td>
            </tr>
            <tr>
              <td><fmt:message key="page.cabinet.newpass2"/> </td>
              <td><input type="password" name="newpass2" size="15" maxlength="15"></td>
            </tr>
            <tr>
              <td colspan="2"><input type="submit" name="submit" value="Change"> </td>
            </tr>
          </table>
        </form>
        <a href="#close" title="Закрыть">Закрыть</a>
      </div>
    </aside>
    ${result}
  </section>
  <section id="content2">
    <c:choose>
      <c:when test="${sessionScope.account.cabinet==null}">
        <fmt:message key="page.cabinet.message.null-account"/>
      </c:when>
      <c:otherwise>
        <jsp:useBean id="tariffPlan" class="by.epam.terehovich.internetprovider.dao.TariffDAO" scope="page"/>
        <table>
          <tr>
            <td><fmt:message key="page.cabinet.operations.tariff"/> </td>
            <td>${sessionScope.account.cabinet.tariffName}</td>
          </tr>
          <tr>
            <td><fmt:message key="page.cabinet.money"/> </td>
            <td>${sessionScope.account.cabinet.money}</td>
          </tr>
          <tr>
            <td><fmt:message key="page.cabinet.status"/> </td>
            <td><c:choose>
              <c:when test="${sessionScope.account.cabinet.status==1}">
                <fmt:message key="page.cabinet.status.active"/>
              </c:when>
              <c:otherwise>
                <fmt:message key="page.cabinet.status.paused"/>
              </c:otherwise>
            </c:choose></td>
          </tr>
        </table>
      </c:otherwise>
    </c:choose>
  </section>
  <section id="content3">
    <c:choose>
      <c:when test="${sessionScope.account.cabinet==null}">
        <form action="${pageContext.request.contextPath}/control" name="connect" method="post">
          <input name="command" type="hidden" value="connect">
          <select name="tariff" onselect="submit()">
          <jsp:useBean id="allTariffs" class="by.epam.terehovich.internetprovider.dao.TariffDAO" scope="page"/>
          <c:forEach items="${allTariffs.findAll()}" var = "tariff">
            <option value="${tariff.id}">${tariff.name}</option>
          </c:forEach>
          </select>
          <input name="submit" type="submit" value="<fmt:message key="page.cabinet.operations.activate"/> ">
        </form>
      </c:when>
      <c:otherwise>
      <c:choose>
          <c:when test="${sessionScope.account.cabinet.status == 1}">
            <form name = "pause" action="${pageContext.request.contextPath}/control" method="post">
              <input name="command" type="hidden" value="changestatus">
              <input name="submit" type="submit" value="<fmt:message key="page.cabinet.operations.pause"/> ">
            </form>
          </c:when>
          <c:otherwise>
      <form name = "pause" action="${pageContext.request.contextPath}/control" method="post">
        <input name="command" type="hidden" value="changestatus">
        <input name="submit" type="submit" value="<fmt:message key="page.cabinet.operations.activate"/> ">
      </form>
          </c:otherwise>
      </c:choose>
      <a href="#payment" class="openModal"><fmt:message key="page.cabinet.operations.payment"/> </a>
      <aside id="payment" class="modal">
        <div>
          <form action="${pageContext.request.contextPath}/control" method="post" name="change-password" class="form-registration">
            <input name="command" type="hidden" value="payment">
                <td><fmt:message key="page.cabinet.operations.payment.sum"/> </td>
                <td><input type="text" name="sum" size="15" maxlength="15"></td>
              <input type="submit" name="submit" value="<fmt:message key="page.cabinet.operations.payment"/> ">
          </form>
          <a href="#close" title="Закрыть">Закрыть</a>
        </div>
      </aside>
      </c:otherwise>
    </c:choose>

</div>
  </section>
</div>


</body>
</html>

src/main/webapp/jsp/tariffs.jsp
<%@page contentType="text/html; charset = utf-8" pageEncoding="UTF-8" session="true" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="customtags" prefix="ctd"%>

<fmt:setLocale value="${sessionScope.lang}" scope="session"/>
<fmt:setBundle basename="localization"/>
<html>
<html>
<head>
  <title><fmt:message key="page.tariffs.title"/> </title>
  <link rel="stylesheet" href="${pageContext.request.contextPath}/css/modal.css" type="text/css">
  <link rel="stylesheet" href="${pageContext.request.contextPath}/css/style/style.css" type="text/css">
  <link rel="stylesheet" href="${pageContext.request.contextPath}/css/tabs/tabs.css" type="text/css">
</head>
<body>
  <c:import url="${pageContext.request.contextPath}/jsp/patterns/header.jsp"/>
  <br>
  <fmt:message key="page.tariffs.welcome"/>
  <br>
  <jsp:useBean id="allTariffs" class="by.epam.terehovich.internetprovider.dao.TariffDAO"/>
  <c:forEach items="${allTariffs.findAll()}" var="tariff">
    <table class="form-signin">
      <tr>
        <td colspan="2">${tariff.name}</td>
      </tr>
      <tr>
        <td><fmt:message key="page.admin-cabinet.tariff.licence-fee"/> </td>
        <td>${tariff.licenseFee}</td>
      </tr>
      <tr>
        <td><fmt:message key="page.admin-cabinet.tariff.speed"/> </td>
        <td>${tariff.speed} </td>
      </tr>
      <c:choose>
        <c:when test="${tariff.traffic==0}">
          <tr>
            <td><fmt:message key="page.admin-cabinet.tariff.Traffic"/> </td>
            <td>&#8734;</td>
          </tr>
        </c:when>
        <c:otherwise>
          <tr>
            <td><fmt:message key="page.admin-cabinet.tariff.Traffic"/> </td>
            <td>${tariff.traffic}</td>
          </tr>
        </c:otherwise>
      </c:choose>
    </table>
  </c:forEach>
</body>
</html>